apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
spec:
  description: Core homelab platform services and shared infrastructure.
  sourceRepos:
    - git@github.com:jerkfacecodemonkey/lab.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: adguard-home
      server: https://kubernetes.default.svc
    - namespace: excalidraw
      server: https://kubernetes.default.svc
    - namespace: keycloak
      server: https://kubernetes.default.svc
    - namespace: openbao
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
