apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard-home.fullname" . }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.service.webPort }}
      targetPort: web
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePorts.web }}
      {{- end }}
    - name: setup
      protocol: TCP
      port: {{ .Values.service.setupPort }}
      targetPort: setup
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePorts.setup }}
      {{- end }}
