replicaCount: 1

image:
  repository: excalidraw/excalidraw
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

env: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
