apiVersion: v2
name: external-secrets
description: Wrapper chart for installing External Secrets Operator
type: application
version: 0.1.0
appVersion: "v2.2.0"

dependencies:
  - name: external-secrets
    version: ">=2.2.0 <2.3.0"
    repository: https://charts.external-secrets.io
