apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-logstash
  namespace: argocd
  labels:
    homelab.donethanks.com/project: pipeline
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: pipeline
  source:
    repoURL: git@github.com:jerkfacecodemonkey/lab.git
    targetRevision: HEAD
    path: projects/pipeline/charts/logstash
    helm:
      releaseName: logstash
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
