apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-strimzi-operator
  namespace: argocd
  labels:
    homelab.donethanks.com/project: pipeline
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: pipeline
  source:
    repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 0.50.0
    helm:
      releaseName: strimzi-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
