{{- if and .Values.keycloak.enabled .Values.keycloak.adminSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.adminSecret.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.keycloak.adminSecret.username | quote }}
  password: {{ .Values.keycloak.adminSecret.password | quote }}
{{- end }}
