{{- if .Values.keycloak.adminSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.adminSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.keycloak.adminSecret.username }}
  password: {{ .Values.keycloak.adminSecret.password | default (randAlphaNum 16) }}
{{- end }}
