{{- if .Values.keycloak.realmImport.enabled }}
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: master-realm-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  keycloakCRName: keycloak
  realm:
    id: master
    realm: master
    enabled: true
    
    # Set browser flow to use passkeys
    browserFlow: browser-passwordless
    
    # Authentication flows
    authenticationFlows:
      - alias: browser-passwordless
        description: Browser based authentication with passkey support
        providerId: basic-flow
        topLevel: true
        builtIn: false
        authenticationExecutions:
          - authenticator: auth-cookie
            authenticatorFlow: false
            requirement: ALTERNATIVE
            priority: 10
            autheticatorFlow: false
          
          - authenticator: auth-spnego
            authenticatorFlow: false
            requirement: DISABLED
            priority: 20
            autheticatorFlow: false
          
          - authenticator: identity-provider-redirector
            authenticatorFlow: false
            requirement: ALTERNATIVE
            priority: 25
            autheticatorFlow: false
          
          - flowAlias: browser-passwordless-forms
            requirement: ALTERNATIVE
            priority: 30
            autheticatorFlow: true
      
      - alias: browser-passwordless-forms
        description: Username, password, passkey and other auth forms
        providerId: basic-flow
        topLevel: false
        builtIn: false
        authenticationExecutions:
          - authenticator: auth-username-form
            authenticatorFlow: false
            requirement: REQUIRED
            priority: 10
            autheticatorFlow: false
          
          - flowAlias: browser-passwordless-authentication
            requirement: REQUIRED
            priority: 20
            autheticatorFlow: true
      
      - alias: browser-passwordless-authentication
        description: Passkey or Password authentication
        providerId: basic-flow
        topLevel: false
        builtIn: false
        authenticationExecutions:
          - authenticator: webauthn-authenticator-passwordless
            authenticatorFlow: false
            requirement: ALTERNATIVE
            priority: 10
            autheticatorFlow: false
          
          - authenticator: auth-password-form
            authenticatorFlow: false
            requirement: ALTERNATIVE
            priority: 20
            autheticatorFlow: false
          
          - flowAlias: Browser - Conditional OTP
            requirement: CONDITIONAL
            priority: 30
            autheticatorFlow: true
    
    # Required actions
    requiredActions:
      - alias: webauthn-register-passwordless
        name: Webauthn Register Passwordless
        providerId: webauthn-register-passwordless
        enabled: true
        defaultAction: false
        priority: 80
      
      - alias: webauthn-register
        name: Webauthn Register
        providerId: webauthn-register
        enabled: true
        defaultAction: false
        priority: 90
    
    # WebAuthn Passwordless Policy
    webAuthnPolicyPasswordlessRpEntityName: {{ .Values.keycloak.hostname }}
    webAuthnPolicyPasswordlessSignatureAlgorithms:
      - ES256
      - RS256
    webAuthnPolicyPasswordlessRpId: {{ .Values.keycloak.hostname }}
    webAuthnPolicyPasswordlessAttestationConveyancePreference: none
    webAuthnPolicyPasswordlessAuthenticatorAttachment: cross-platform
    webAuthnPolicyPasswordlessRequireResidentKey: "Yes"
    webAuthnPolicyPasswordlessUserVerificationRequirement: required
    webAuthnPolicyPasswordlessCreateTimeout: 60
    webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister: false
    
    # OIDC Clients
    clients:
      - clientId: argocd
        name: Argo CD
        description: "Argo CD continuous delivery platform"
        enabled: true
        protocol: openid-connect
        publicClient: false
        clientAuthenticatorType: client-secret
        secret: {{ .Values.keycloak.clients.argocd.secret | quote }}
        standardFlowEnabled: true
        implicitFlowEnabled: false
        directAccessGrantsEnabled: false
        serviceAccountsEnabled: false
        redirectUris:
          - "https://argo.donethanks.com/auth/callback"
        webOrigins:
          - "https://argo.donethanks.com"
        defaultClientScopes:
          - profile
          - email
          - roles
        optionalClientScopes:
          - groups
        protocolMappers:
          - name: realm-roles-mapper
            protocol: openid-connect
            protocolMapper: oidc-usermodel-realm-role-mapper
            consentRequired: false
            config:
              claim.name: groups
              jsonType.label: String
              multivalued: "true"
              userinfo.token.claim: "true"
              id.token.claim: "true"
              access.token.claim: "true"
      - clientId: adguard-oauth
        name: AdGuard OAuth Proxy
        description: "OAuth2 Proxy in front of AdGuard Home"
        enabled: true
        protocol: openid-connect
        publicClient: false
        clientAuthenticatorType: client-secret
        secret: {{ .Values.keycloak.clients.adguardOauth.secret | quote }}
        standardFlowEnabled: true
        implicitFlowEnabled: false
        directAccessGrantsEnabled: false
        serviceAccountsEnabled: false
        redirectUris:
          - "https://adguard.donethanks.com/oauth2/callback"
        webOrigins:
          - "https://adguard.donethanks.com"
        defaultClientScopes:
          - profile
          - email
          - roles
        optionalClientScopes:
          - groups
        protocolMappers:
          - name: email-direct
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              user.attribute: email
              claim.name: email
              jsonType.label: String
              userinfo.token.claim: "true"
              id.token.claim: "true"
              access.token.claim: "true"
              introspection.token.claim: "true"
          - name: audience-direct
            protocol: openid-connect
            protocolMapper: oidc-audience-mapper
            consentRequired: false
            config:
              included.client.audience: adguard-oauth
              id.token.claim: "true"
              access.token.claim: "true"
      - clientId: traefik-oauth
        name: Traefik Dashboard OAuth Proxy
        description: "OAuth2 Proxy in front of Traefik dashboard"
        enabled: true
        protocol: openid-connect
        publicClient: false
        clientAuthenticatorType: client-secret
        secret: {{ .Values.keycloak.clients.traefikOauth.secret | quote }}
        standardFlowEnabled: true
        implicitFlowEnabled: false
        directAccessGrantsEnabled: false
        serviceAccountsEnabled: false
        redirectUris:
          - "https://traefik.donethanks.com/oauth2/callback"
        webOrigins:
          - "https://traefik.donethanks.com"
        defaultClientScopes:
          - profile
          - email
          - roles
        optionalClientScopes:
          - groups
        protocolMappers:
          - name: email-direct
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              user.attribute: email
              claim.name: email
              jsonType.label: String
              userinfo.token.claim: "true"
              id.token.claim: "true"
              access.token.claim: "true"
              introspection.token.claim: "true"
          - name: audience-direct
            protocol: openid-connect
            protocolMapper: oidc-audience-mapper
            consentRequired: false
            config:
              included.client.audience: traefik-oauth
              id.token.claim: "true"
              access.token.claim: "true"
{{- end }}
