apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kafka.name }}-kafka
  namespace: {{ .Values.kafkaNamespace }}
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ .Values.kafka.name }}
    app.kubernetes.io/managed-by: Helm
