apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-demo
  namespace: openbao
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: openbao-demo-synced
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: lab/demo
        property: username
    - secretKey: password
      remoteRef:
        key: lab/demo
        property: password
