apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao
  namespace: openbao
spec:
  provider:
    vault:
      server: http://openbao.openbao.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: openbao-eso-token
          key: token
