apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-tls-default
  namespace: argocd
spec:
  project: core
  source:
    repoURL: git@github.com:jerkfacecodemonkey/lab.git
    targetRevision: HEAD
    path: argocd/infra/traefik-tls-default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
