apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  labels:
    {{- include "elastic.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: {{ .Values.elasticsearch.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: elasticsearch
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "elastic.labels" . | nindent 8 }}
        app.kubernetes.io/component: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
          imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9200
            - name: transport
              containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: {{ ternary "true" "false" .Values.security.enabled | quote }}
            {{- if .Values.security.enabled }}
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "elastic.securitySecretName" . }}
                  key: elastic-password
            {{- end }}
            - name: ES_JAVA_OPTS
              value: {{ .Values.elasticsearch.javaOpts | quote }}
            - name: cluster.name
              value: "elastic-local"
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.elasticsearch.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
  {{- if .Values.elasticsearch.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.elasticsearch.persistence.size }}
        {{- if .Values.elasticsearch.persistence.storageClass }}
        storageClassName: {{ .Values.elasticsearch.persistence.storageClass | quote }}
        {{- end }}
  {{- else }}
      volumes:
        - name: data
          emptyDir: {}
  {{- end }}
