apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  labels:
    {{- include "elastic.labels" . | nindent 4 }}
    app.kubernetes.io/component: kibana
spec:
  replicas: {{ .Values.kibana.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: kibana
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "elastic.labels" . | nindent 8 }}
        app.kubernetes.io/component: kibana
    spec:
      containers:
        - name: kibana
          image: "{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}"
          imagePullPolicy: {{ .Values.kibana.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch.{{ .Values.namespace }}.svc.cluster.local:9200
            - name: XPACK_SECURITY_ENABLED
              value: {{ ternary "true" "false" .Values.security.enabled | quote }}
            {{- if .Values.security.enabled }}
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "elastic.securitySecretName" . }}
                  key: kibana-username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "elastic.securitySecretName" . }}
                  key: kibana-password
            {{- end }}
            {{- if .Values.security.oidc.enabled }}
            - name: XPACK_SECURITY_AUTHC_PROVIDERS_OIDC_OIDC1_ORDER
              value: "0"
            - name: XPACK_SECURITY_AUTHC_PROVIDERS_OIDC_OIDC1_REALM
              value: {{ .Values.security.oidc.realm | quote }}
            - name: XPACK_SECURITY_AUTHC_PROVIDERS_BASIC_BASIC1_ORDER
              value: "1"
            {{- end }}
            - name: SERVER_PUBLICBASEURL
              value: https://{{ .Values.ingress.kibanaHost }}
          readinessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.kibana.resources | nindent 12 }}
