{{- if and .Values.security.enabled .Values.security.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elastic.securitySecretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "elastic.labels" . | nindent 4 }}
type: Opaque
stringData:
  elastic-username: {{ .Values.security.elastic.username | quote }}
  elastic-password: {{ .Values.security.elastic.password | quote }}
  kibana-username: {{ .Values.security.kibana.username | quote }}
  kibana-password: {{ .Values.security.kibana.password | quote }}
  kibana-encryptedsavedobjects-encryption-key: {{ .Values.security.kibana.encryptedSavedObjectsKey | quote }}
{{- end }}
